name: "Unity Build Action"
description: "Build Android, iOS, Mac, Windows, and WebGL"
inputs:
  unity-version:
    description: "For example, 2018.4.16f1"
    required: true
  unity-username:
    description: "Unity username"
    required: true
  unity-password:
    description: "Unity password"
    required: true
  unity-serial:
    description: "Unity serial"
    required: true
  build-target:
    description: "Choose android, ios, windows, webgl, etc"
    required: true
  changeset:
    description: "Required for Unity Hub, available at the bottom of Unity's Release Note"
    required: true
  project-path:
    description: "Unity project path"
    required: false
    default: .
  execute-method:
    description: "Use by -executeMethod"
    required: false
    default: UnityBuild.BatchBuild.Build
  output-path:
    description: "Output path of default execute-method"
    required: false
    default: Output
  command-args:
    description: "Build command args"
    required: false
runs:
  using: "node12"
  main: "build.js"
  post: "returnlicense.js"
